baseURL = "http://example.org/"
languageCode = "en-us"
title = "FirstSite"
theme = "ananke"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about FirstSite"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110

  
  [build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
